// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1MdEHfRIMkOzvhTTpN57aEO2F4GNoPmM',
    appId: '1:801929081006:web:fcdcf26fe0cfc2c9c57d3f',
    messagingSenderId: '801929081006',
    projectId: 'fir-crud-a020e',
    authDomain: 'fir-crud-a020e.firebaseapp.com',
    storageBucket: 'fir-crud-a020e.appspot.com',
    measurementId: 'G-GCCE05HH2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9HRjYCSam9QrzafqkiQlRx2SEshZDzhI',
    appId: '1:801929081006:android:5761688df998c139c57d3f',
    messagingSenderId: '801929081006',
    projectId: 'fir-crud-a020e',
    storageBucket: 'fir-crud-a020e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgeu3PCGpgiBKwFITukhXGPz5c9ssYP1c',
    appId: '1:801929081006:ios:65aa5c043668956dc57d3f',
    messagingSenderId: '801929081006',
    projectId: 'fir-crud-a020e',
    storageBucket: 'fir-crud-a020e.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgeu3PCGpgiBKwFITukhXGPz5c9ssYP1c',
    appId: '1:801929081006:ios:65aa5c043668956dc57d3f',
    messagingSenderId: '801929081006',
    projectId: 'fir-crud-a020e',
    storageBucket: 'fir-crud-a020e.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1MdEHfRIMkOzvhTTpN57aEO2F4GNoPmM',
    appId: '1:801929081006:web:9492b6a98dc92b0ec57d3f',
    messagingSenderId: '801929081006',
    projectId: 'fir-crud-a020e',
    authDomain: 'fir-crud-a020e.firebaseapp.com',
    storageBucket: 'fir-crud-a020e.appspot.com',
    measurementId: 'G-N03XGMB349',
  );
}
